#server:
#  port: 80

spring:
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    mode: HTML5
    suffix: .html
    cache: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/admin
    username: root 
    password: rharhaelql 
  jpa:
    show-sql: true
